# Generated by Django 5.1.7 on 2025-04-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=255)),
                ('student_last_name', models.CharField(max_length=255)),
                ('test_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('reviewed', models.BooleanField(default=False)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
